// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofnwvyxolilyrcyiafdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mbnd2eXhvbGlseXJjeWlhZmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDI2NjcsImV4cCI6MjA2Mjc3ODY2N30.2QmyTZMBwb8fGyZzCf5xeCYl6RoFo1jWfytgtr3Ieeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);